<?php
ini_set('error_reporting',1);
require_once("${strPathToIncludes}FileMaker.php");
require_once("${strPathToIncludes}dbFunctions.php");

define('DATABASE_HOST', '140.247.100.254');
define('DATABASE_NAME', 'WLP');
define('DATABASE_USER', 'web');
define('DATABASE_PASSWORD', 'Wh!t3L@vy'); //DB NAME


//create the FileMaker Object
$fm = & new FileMaker(DATABASE_NAME, DATABASE_HOST);
$fm->setProperty('username', DATABASE_USER );
$fm->setProperty('password', DATABASE_PASSWORD );

$otherPhoneTypes = array();
$otherPhoneTypes['Home'] = 'Home';
$otherPhoneTypes['Cell'] = 'Cell';
$otherPhoneTypes['Work'] = 'Work';

$countries = array("Afghanistan","Albania","Algeria","American Samoa","Andorra","Angola","Anguilla","Antarctica","Antigua and Barbuda","Argentina", "Armenia","Aruba","Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize" 
               ,"Benin" ,"Bermuda" 
               ,"Bhutan","Bolivia"
                
               ,"Bosnia and Herzegovina"
               ,"Botswana"
               ,"Bouvet Island"
               ,"Brazil" 
               ,"British Indian Ocean Territory" 
               ,"Brunei"
               ,"Bulgaria" 
               ,"Burkina Faso" 
               ,"Burundi"
                
               ,"Cambodia" 
               ,"Cameroon" 
               ,"Canada" 
               ,"Cape Verde" 
               ,"Cayman Islands"
               ,"Central African Republic" 
               ,"Chad" 
               ,"Chile" 
               ,"China"
                
               ,"Christmas Island" 
               ,"Cocos (Keeling) Islands" 
               ,"Colombia" 
               ,"Comoros" 
               ,"Congo" 
               ,"Cook Islands" 
               ,"Costa Rica"
               ,"Cote d'Ivoire" 
               ,"Croatia (Hrvatska)"
                
               ,"Cuba" 
               ,"Cyprus" 
               ,"Czech Republic"
               ,"Congo (DRC)" 
               ,"Denmark" 
               ,"Djibouti" 
               ,"Dominica" 
               ,"Dominican Republic" 
               ,"East Timor" 
                
               ,"Ecuador" 
               ,"Egypt" 
               ,"El Salvador" 
               ,"Equatorial Guinea" 
               ,"Eritrea" 
               ,"Estonia" 
               ,"Ethiopia" 
               ,"Falkland Islands (Islas Malvinas)" 
               ,"Faroe Islands"
                
               ,"Fiji Islands"
               ,"Finland" 
               ,"France" 
               ,"French Guiana" 
               ,"French Polynesia" 
               ,"French Southern and Antarctic Lands" 
               ,"Gabon"
               ,"Gambia" 
               ,"Georgia" 
                
               ,"Germany" 
               ,"Ghana"
               ,"Gibraltar"
               ,"Greece" 
               ,"Greenland" 
               ,"Grenada"
               ,"Guadeloupe" 
               ,"Guam" 
               ,"Guatemala" 
                
               ,"Guinea" 
               ,"Guinea-Bissau" 
               ,"Guyana" 
               ,"Haiti" 
               ,"Heard Island and McDonald Islands" 
               ,"Honduras" 
               ,"Hong Kong SAR" 
               ,"Hungary" 
               ,"Iceland"
                
               ,"India" 
               ,"Indonesia" 
               ,"Iran" 
               ,"Iraq"
               ,"Ireland" 
               ,"Israel" 
               ,"Italy" 
               ,"Jamaica" 
               ,"Japan" 
                
               ,"Jordan" 
              ,"Kazakhstan" 
               ,"Kenya" 
               ,"Kiribati"
               ,"Korea" 
               ,"Kuwait" 
               ,"Kyrgyzstan" 
               ,"Laos" 
               ,"Latvia" 
                
               ,"Lebanon" 
               ,"Lesotho" 
               ,"Liberia" 
               ,"Libya" 
               ,"Liechtenstein" 
               ,"Lithuania"
               ,"Luxembourg" 
               ,"Macao SAR" 
               ,"Macedonia"
                
               ,"Madagascar" 
               ,"Malawi"
               ,"Malaysia"
               ,"Maldives" 
               ,"Mali" 
               ,"Malta" 
               ,"Marshall Islands" 
               ,"Martinique" 
               ,"Mauritania"
                
               ,"Mauritius" 
               ,"Mayotte" 
               ,"Mexico" 
               ,"Micronesia" 
               ,"Moldova" 
               ,"Monaco" 
               ,"Mongolia" 
               ,"Montserrat" 
               ,"Morocco" 
                
               ,"Mozambique" 
               ,"Myanmar" 
               ,"Namibia" 
               ,"Nauru"
               ,"Nepal"
               ,"Netherlands" 
               ,"Netherlands Antilles" 
               ,"New Caledonia" 
               ,"New Zealand" 
                
               ,"Nicaragua" 
               ,"Niger"
               ,"Nigeria"
               ,"Niue" 
               ,"Norfolk Island" 
               ,"North Korea" 
               ,"Northern Mariana Islands" 
               ,"Norway" 
               ,"Oman" 
               
               ,"Pakistan" 
               ,"Palau" 
               ,"Panama" 
               ,"Papua New Guinea" 
               ,"Paraguay" 
               ,"Peru" 
               ,"Philippines" 
               ,"Pitcairn Islands"
               ,"Poland" 
                
               ,"Portugal"
               ,"Puerto Rico"
               ,"Qatar" 
               ,"Reunion" 
               ,"Romania" 
               ,"Russia"
               ,"Rwanda"
               ,"Samoa" 
               ,"San Marino" 
                
               ,"Sao Tome and Principe" 
               ,"Saudi Arabia" 
               ,"Senegal" 
               ,"Serbia and Montenegro" 
               ,"Seychelles" 
               ,"Sierra Leone" 
               ,"Singapore"
               ,"Slovakia"
               ,"Slovenia" 
                
               ,"Solomon Islands"
               ,"Somalia" 
               ,"South Africa" 
               ,"South Georgia" 
               ,"Spain" 
               ,"Sri Lanka" 
               ,"St. Helena"
               ,"St. Kitts and Nevis" 
               ,"St. Lucia" 
               
              ,"St. Pierre and Miquelon" 
              , "St. Vincent and the Grenadines" 
              , "Sudan" 
              , "Suriname" 
              , "Svalbard and Jan Mayen" 
              , "Swaziland" 
              , "Sweden"
             ,  "Switzerland" 
              , "Syria" 
              
              , "Taiwan" 
               ,"Tajikistan"
              , "Tanzania" 
              , "Thailand" 
              , "Togo" 
              , "Tokelau"
              , "Tonga"
              , "Trinidad and Tobago"
               ,"Tunisia"
               
               ,"Turkey" 
               ,"Turkmenistan" 
               ,"Turks and Caicos Islands" 
               ,"Tuvalu" 
              , "Uganda"
              , "Ukraine"
              , "United Arab Emirates"
               ,"UK"
               ,"USA" 
                
               ,"United States Minor Outlying Islands"
              , "Uruguay"
              , "Uzbekistan" 
               ,"Vanuatu"
              , "Venezuela" 
               ,"Viet Nam" 
              , "Virgin Islands (British)" 
               
             ,  "Wallis and Futuna"
              , "Yemen"
              , "Zambia"
              , "Zimbabwe");

?>

