<div class="col c2">  	   
        <div align="center"><img src="http://www.fas.harvard.edu/~semitic/wl/images/footerstone.png" width="79" height="75" />
		
		</div></div>
	
        
      <div class="col c3" align="left">
<h6 align="center">The Shelby White and Leon Levy Program for Archaeological Publications<br />
        Harvard University, The Semitic Museum. 6 Divinity Avenue, Cambridge, MA         02138 <br />
        Telephone: (617) 495-9317 | Fax: (617) 496-8904 | Email: <a href="mailto:info@whitelevy.org">info@whitelevy.org</a> </h6>
      </div>

      <div class="clr"></div>
	  
	  
	  
    </div>
  </div>
  <div class="footer">
    <div class="footer_resize">
      <p align="left" class="lr style3"><strong>Copyright &copy; 2013 The Semitic Museum - All Rights Reserved</strong></p>
      <div class="clr"></div>
    </div>