<div class="logo">


  <INPUT TYPE="HIDDEN" NAME="index" VALUE="404232">
        <TABLE CELLSPACING=0 CELLPADDING=0 BORDER=0 align="right">
          <TR> 
            <TD><INPUT TYPE="TEXT" NAME="query"  value="" SIZE="20" maxlength="35" style="vertical-align:bottom"></TD>
            <TD><nobr> 
              <input name="search" type="image" style="vertical-align:bottom" src="http://www.fas.harvard.edu/~semitic/wl/images/search.gif" alt="Search" width="56" height="22">
              </nobr></TD>
          </TR>
        </TABLE>
      </FORM>
